/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */ 
    double v[];
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdPares = new javax.swing.JButton();
        cmdImpares = new javax.swing.JButton();
        cmdPrimos = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("ejercicio2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("longitud del vector");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel1.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 50));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("menu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        cmdCrear.setText("crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        cmdManual.setText("llenado manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        cmdAutomatico.setText("llenado automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cmdPares.setText("numeros pares");
        cmdPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdParesActionPerformed(evt);
            }
        });
        jPanel2.add(cmdPares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        cmdImpares.setText("numeros impares");
        cmdImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdImparesActionPerformed(evt);
            }
        });
        jPanel2.add(cmdImpares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, -1));

        cmdPrimos.setText("numeros primos");
        cmdPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrimosActionPerformed(evt);
            }
        });
        jPanel2.add(cmdPrimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        cmdMostrar.setText("mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        cmdBorrar.setText("borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, 350));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("resultados");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 230, 320));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 270, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdParesActionPerformed
        String res;double contpar=0; 
      if(txtLongitud.getText().trim().isEmpty()){ 
          JOptionPane.showMessageDialog(this,"Ingrese la longitud del vector"); 
          txtLongitud.requestFocusInWindow();
      }else{ 
          for (int i = 0; i < v.length; i++) {
              if(v[i]%2==0){ 
             contpar=contpar+1;
              }else{ 
               
              }
          } 
          res=String.valueOf(contpar); 
          txtResultado.setText("La cantidad de numeros pares son:"); 
          txtResultado.append(res);
          
      }
    }//GEN-LAST:event_cmdParesActionPerformed

    private void cmdImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdImparesActionPerformed
       String res;double contimpar=0; 
     if(txtLongitud.getText().trim().isEmpty()){ 
      JOptionPane.showMessageDialog(this,"Ingrese longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
      txtResultado.requestFocusInWindow();
     }else{ 
         for (int i = 0; i < v.length; i++) {
          if(v[i]%2!=0){ 
           contimpar=contimpar+1;
          }
         } 
        res=String.valueOf(contimpar); 
        txtResultado.setText("La cantidad de numeros impares es:");
        txtResultado.append(res);
         
     }
    }//GEN-LAST:event_cmdImparesActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud; 
      if(txtLongitud.getText().trim().isEmpty()){ 
       JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
       txtLongitud.requestFocusInWindow();
      }else if(Integer.parseInt(txtLongitud.getText().trim())==0){ 
        JOptionPane.showMessageDialog(this,"La longitud no puede ser cero","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow(); 
        txtLongitud.selectAll();
      }else{ 
        longitud=Integer.parseInt(txtLongitud.getText()); 
        v=new double[longitud]; 
        JOptionPane.showConfirmDialog(this,"Vector creado satisfactoriamente");
      }        
        
      
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       if(txtLongitud.getText().trim().isEmpty()){ 
         JOptionPane.showConfirmDialog(this,"Ingrese la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       }else{ 
           for (int i = 0; i <v.length; i++) { 
              txtResultado.append(v[i]+"\n");
               
           }
       }
       
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        double llenado; 
       if(txtLongitud.getText().trim().isEmpty()){ 
        JOptionPane.showConfirmDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow();
       }else{ 
           for (int i = 0; i < v.length; i++) {
          llenado=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el elemento en la posicion:"+i));
          v[i]=llenado;
               
           }
       }
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
      double llenado,numero; 
    if(txtLongitud.getText().trim().isEmpty()){ 
     JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
     txtLongitud.requestFocusInWindow();
    }else{ 
      numero=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el numero hasta donde desee el llenado automatico"));
      while(numero<v.length){ 
       JOptionPane.showConfirmDialog(this,"Ingrese numero mayor a:"+v.length); 
       numero=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el numero hasta donde desee el llenado automatico"));
       
      } 
        for (int i = 0; i < v.length; i++) {
         llenado=(int) (Math.random()*numero+1); 
         v[i]=llenado;
            
        } 
        JOptionPane.showConfirmDialog(this,"Vector llenado satisfactoriamente");
    }
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrimosActionPerformed
       String res;double contprimo=0; 
      if(txtLongitud.getText().trim().isEmpty()){ 
       JOptionPane.showConfirmDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
       txtLongitud.requestFocusInWindow();
      }else{ 
          for (int i = 0; i < v.length; i++) {
             if(v[i]%v[i]==0&&v[i]%2!=0){ 
              contprimo=contprimo+1;
             }else{ 
              
             } 
             res=String.valueOf(contprimo); 
             txtResultado.setText("La cantidad de numeros primos es:"); 
             txtResultado.append(res);
              
          }
      }
    }//GEN-LAST:event_cmdPrimosActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtLongitud.setText(""); 
        txtResultado.setText(""); 
        txtLongitud.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
       char c=evt.getKeyChar(); 
      if(!Character.isDigit(c)){ 
        getToolkit().beep(); 
      evt.consume();
        
      }
    }//GEN-LAST:event_txtLongitudKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdImpares;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdPares;
    private javax.swing.JButton cmdPrimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
